Added FluentMigrator. Added api/service for working with events
Strelchenko/Infotecs.ConnectionMonitoring pull request #4
Opened 2022-04-12 12:30 UTC by Strelchenko

2022-04-12 13:35 UTC, adcy requested changes

2022-04-12 13:35 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +public class ConnectionEvent
Меня ConnectionEvent вводит в заблуждение. Из названия выходит что это событие соединения - по смыслу от отличается того, что в задании. В задании идет речь о приложении, которое называется Connect. Может тогда назвать ConnectEvent? Или ApplicationEvent?

2022-04-12 13:35 UTC, adcy commented on Infotecs.ConnectionMonitoring/Data/Services/ConnectionEventService.cs
> +                logger.LogError(e, "Event saving error {@ConnectionEvent}", connectionEvent);
Исключения обязательно нужно пробрасывать наверх.

2022-04-12 13:35 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +    public string? Id { get; set; }
Кажется идентификатор события в описании предметной области не фигурирует. Если он требуется для хранения в БД, то нужно оставить его только в модели БД.
Аналогично поле ConnectionId ниже, видимо оно появилось для того чтобы соотносить записи в реляционной БД. Такие поля по возможности нужно оставлять на уровне БД моделей. (Причем в данном случае это нужно из-за того что БД реляционная, если бы использовалась mongo, например, то в ConnectionId не было бы необходимости.

2022-04-12 13:35 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Services/IConnectionEventService.cs
> +    Task SaveAsync(IEnumerable<ConnectionEvent> connectionEvents);
Неконсистентное наименование методов. В одном случае просто Save, в другом Get**Events**, лучше сделать единообразно как-то.

2022-04-12 13:35 UTC, adcy commented on Infotecs.ConnectionMonitoring/Data/Migrations/MigrationManager.cs
> +                logger.LogError(ex, "Error migration");
Исключение должно пробрасываться наверх.

2022-04-12 13:35 UTC, adcy commented on Infotecs.ConnectionMonitoring/Data/Migrations/InitialTables202204120001.cs
> +            .WithColumn("Id").AsString(256).NotNullable().PrimaryKey()
В postgresql принято именовать таблицы и столбцы в snake_case. Но это не критично, можно и так. Просто в таком варианте придется всегда имена брать в кавычки, а в случае snake_case имен кавычки в большинстве случаев можно опускать.

2022-04-12 13:35 UTC, adcy commented on Infotecs.ConnectionMonitoring/WebApi/Controllers/ConnectionEventController.cs
> +        return Ok(connectionEvents);
Не обязательно возвращать ActionResult. Можно напрямую возвращать список ConnectionEvent[], asp net сам сериализует их в json и код ответа будет 200 ОК.

2022-04-12 14:25 UTC, Strelchenko commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +public class ConnectionEvent
Ну в заданиях речь идет вообще все время о разном. То это устройство, то узел, то нода, еще что-нибудь. Отсюда и путаница. В начале назвал основную сющность как Connection, поэтому теперь придерживаюсь этого названия. Отсюда и название для ивента такое.

2022-04-12 14:27 UTC, Strelchenko commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +    public string? Id { get; set; }
В задании фигурирует только два поля. Но когда мне придет массив ивентов, как я определю кокой ивент к какому устройсву/узлу/тд относится?

2022-04-12 14:33 UTC, Strelchenko commented on Infotecs.ConnectionMonitoring/Data/Services/ConnectionEventService.cs
> +                logger.LogError(e, "Event saving error {@ConnectionEvent}", connectionEvent);
Тут мне не нужно прерывать выполнение метода. Так как из 1000 ивентов может быть только один с ошибкой. И я не запишу только его, а не все 1000.

2022-04-12 14:40 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +public class ConnectionEvent
>> То это устройство, то узел, то нода
Вроде +\- схожие понятия? Явно не соединение.

2022-04-12 14:45 UTC, adcy commented on Infotecs.ConnectionMonitoring/Data/Services/ConnectionEventService.cs
> +                logger.LogError(e, "Event saving error {@ConnectionEvent}", connectionEvent);
Проблема такого подхода в том, что можно вообще ничего не записывать и не заметить этого. Например потому что БД отвалилась. АПИ при этом будет всегда 200 возвращать.

2022-04-12 14:46 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +    public string? Id { get; set; }
> кокой ивент к какому устройсву/узлу/тд относится

В принципе можно разными способами. Но ок, справедливо, так как сейчас тоже можно. 
А поле Id нужно здесь?

2022-04-12 14:51 UTC, Strelchenko commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +    public string? Id { get; set; }
Ну я не знаю что там в заданиях 5-8. Я не вижу цельной картины. Пока не надо. Но не думаю что это кому-то мешает. Могу убрать

2022-04-12 14:53 UTC, Strelchenko commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +    public string? Id { get; set; }
Но я использую в сервисе это Id для генерации ID перед записью в бд

2022-04-12 14:54 UTC, Strelchenko commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +public class ConnectionEvent
Ну когда явно, тогда нет +-, а явно написано что это.

2022-04-12 15:33 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +    public string? Id { get; set; }
Ок, пусть будет. Не мешает.

2022-04-12 15:40 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +public class ConnectionEvent
Если явно не написано, то это повод выбрать совершенно левое имя? Если совсем непонятно какой это event, то можно и оставить просто Event.

2022-04-12 15:55 UTC, Strelchenko commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +public class ConnectionEvent
Тут оно не левое. Тут оно конкретно относится к сущности, которая была создана ранее - это ConnectionInfo. Ивен относится к нему, соответсвенно это ConnectionEvent. Если переименовывать эту сущность, то переименовывать и все остальные и проект. И не только этот, но и фронт. Если будет свободное время после выполнения всех заданий, то может займусь этим

2022-04-12 16:00 UTC, adcy commented on Infotecs.ConnectionMonitoring/Core/Models/ConnectionEvent.cs
> +public class ConnectionEvent
хорошо

2022-04-13 06:09 UTC, adcy approved these changes

2022-04-13 07:03 UTC, merged